### ISSUE TITLE
can you re-compile for 64bit Notepad++ on Windows 10

### ISSUE THREAD

**Issue by radarmanau** [lygstate/NotepadStarter#3]
Hi, loaded NotepadStarter plugin and got the following error;

Running Windows 10 Pro, Notepad++ x64 v7.3.3
![npp notepad starter error](https://cloud.githubusercontent.com/assets/26447369/23976928/afc0fbc4-0a36-11e7-872d-c8418122751e.jpg)

**Comment by lygstate** [comment]
OK, I'll consider that.

**Comment by reibuehl** [comment]
+1

**Comment by ALIENQuake** [comment]
@reibuehl This is very userful plugin because it doesn't modify files itself. How about a Christmas present for us?

**Comment by zapy85** [comment]
@ALIENQuake just use http://www.binaryfortress.com/notepadreplacer/ instead, this project is dead, linked project is newer and updated in september 2017.

**Comment by lygstate** [comment]
chrismas  make sense

**Comment by lygstate** [comment]
Compiled one with contributions from @chcg .

**Comment by lygstate** [comment]
Anyone give me some feedback?

**Comment by ALIENQuake** [comment]
@lygstate Works on Windows 10 17083

**Comment by lygstate** [comment]
@ALIENQuake  64bit version?

**Comment by chcg** [comment]
@lygstate I added release 2.3.1.0 to the plugin manager x64 list, see https://github.com/bruderstein/npp-plugins-x64/commit/9e73ef926013f42b5e64683fc9770df6ed35f394 and also for x86 at https://npppm.bruderste.in/plugins/view/notepadstarterplugin. Is this ok for you?

**Comment by chcg** [comment]
@lygstate I added release 2.3.1.0 to the plugin manager x64 list, see https://github.com/bruderstein/npp-plugins-x64/commit/9e73ef926013f42b5e64683fc9770df6ed35f394 and also for x86 at https://npppm.bruderste.in/plugins/view/notepadstarterplugin. Is this ok for you?

**Comment by ALIENQuake** [comment]
@lygstate Thanks for effort. May I suggest to recompile plugin statically, without dependency from VC++ Redistributable ?

**Comment by chcg** [comment]
@lygstate @ALIENQuake See https://github.com/lygstate/NotepadStarter/blob/master/plugin/NotepadStarterPlugin.vcxproj#L144 this option was not taken over on copying the config within VS. The same for https://github.com/lygstate/NotepadStarter/blob/master/starter/NotepadStarter.vcxproj#L131

**Comment by lygstate** [comment]
Oh I see , I forgot setting the option for the 64bit version, but setting for the 32bit version

**Comment by lygstate** [comment]
That's why the 64bit binary are smaller than the 32 bit version

**Comment by lygstate** [comment]
@ALIENQuake try the newest version, @chcg 2.3.2.0 would be more properly

**Comment by ALIENQuake** [comment]
@lygstate Already did, it's working. Thanks.

**Comment by chcg** [comment]
@lygstate Already updated PM list to 2.3.2.0.
